### ISSUE TITLE
Sass Comments

### ISSUE THREAD

**Issue by craigcoles** [truedigital/frontend-guidelines#1]
How do we want to do this?
##### Section Comment Block

```
// === Section
```
##### Inline Comment

```
// Inline comment
```

**Comment by kevrowe** [comment]
I'm a fan of this for blocks, but I'm conscious it's cumbersome to write.

```
// ===============================
// Section
// ===============================
```

Could trim to

```
// Section
// ===============================
```

Just something a little bolder than single a line.
